apiVersion: v2
name: landppt
description: AI-powered PPT generation platform
type: application
version: 0.1.2
appVersion: "0.3.3"
keywords:
  - landppt
  - ppt
  - ai
sources:
  - https://github.com/sligter/LandPPT
